# Astarte config parameters
astarteRealm: "realm"
astartePairingUrl: "astarte_url"
astarteDeviceId: "astarte_device_id"
astarteCredentialsSecret: "astarte_credentials_secret"

# MQTT config parameters
mqttBrokerUri: "tcp://localhost:1883"
mqttClientId: "aggregator"
mqttTopicList: []

# Aggregation Tasks parameter
reportSendRepetitionInSeconds: 300
groupSendRepetitionPeriod: 300
